version: "3.6"
services:
    database:
        image: postgres:11
        env_file:
            - ./env

    tests:
        build:
            context: $PWD/../../..
            dockerfile: $PWD/../backend/Dockerfile
        env_file:
            - ./env
        command: ["run", "test"]
